/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Logro;
import Modelo.Personas.Niño;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Esta clase representa una ventana que asigna un logro a un niño
 * @author JuanZea
 * @version 1.0.0
 * @since Jardin 1.0.2
 */
public class AsignarLogro extends javax.swing.JDialog {

    private Logro logro;
    private boolean señal;
    private int dueño;

    /**
     * Creates new form AsignarLogro
     */
    public AsignarLogro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void rellenarEstudiantes(ArrayList<Niño> niños) {
        for (int i = 0; i < niños.size(); i++) {
            jComboBoxEstudiante.addItem(niños.get(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHoja = new javax.swing.JPanel();
        jComboBoxEstudiante = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNombreLogro = new javax.swing.JTextField();
        jButtonAsignar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Logro");
        setIconImage(new ImageIcon(getClass().getResource("/Vista/img/Icono7.png")).getImage());

        jPanelHoja.setBackground(java.awt.Color.yellow);

        jComboBoxEstudiante.setToolTipText("El profesor que hará el reporte");

        jLabel2.setBackground(java.awt.Color.orange);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Estudiante:");
        jLabel2.setOpaque(true);

        jComboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollo de pensamiento lógico matematico", "Desarrolo de habilidades de análisis", "Desarrolo de habilidades de pensamiento sistémico", "Desarrolo de pensamiento creativo" }));
        jComboCategoria.setToolTipText("El profesor que hará el reporte");

        jLabel3.setBackground(java.awt.Color.orange);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre del Logro:");
        jLabel3.setOpaque(true);

        jLabel8.setBackground(java.awt.Color.orange);
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Categoria del Logro:");
        jLabel8.setOpaque(true);

        jTextFieldNombreLogro.setToolTipText("Ejemplo: Resolver rompecabezas de 29 piezas");

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHojaLayout = new javax.swing.GroupLayout(jPanelHoja);
        jPanelHoja.setLayout(jPanelHojaLayout);
        jPanelHojaLayout.setHorizontalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNombreLogro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelHojaLayout.createSequentialGroup()
                                    .addComponent(jButtonAsignar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCancelar))))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        jPanelHojaLayout.setVerticalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNombreLogro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAsignar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHoja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHoja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        señal = false;
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarActionPerformed
        if (jComboBoxEstudiante.getSelectedIndex() == -1 || jTextFieldNombreLogro.getText().isBlank() || jComboCategoria.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Hacen uno o varios datos");
        } else {
            String nombre = jTextFieldNombreLogro.getText();
            String categoria = jComboCategoria.getItemAt(jComboCategoria.getSelectedIndex());
            dueño = jComboBoxEstudiante.getSelectedIndex();
            logro = new Logro(nombre, categoria, false);
            señal = true;
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarLogro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarLogro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarLogro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarLogro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AsignarLogro dialog = new AsignarLogro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxEstudiante;
    private javax.swing.JComboBox<String> jComboCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelHoja;
    private javax.swing.JTextField jTextFieldNombreLogro;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonAsignar() {
        return jButtonAsignar;
    }

    public javax.swing.JButton getjButtonCancelar() {
        return jButtonCancelar;
    }

    public javax.swing.JComboBox<String> getjComboBoxEstudiante() {
        return jComboBoxEstudiante;
    }

    public javax.swing.JComboBox<String> getjComboCategoria() {
        return jComboCategoria;
    }

    public javax.swing.JTextField getjTextFieldNombreLogro() {
        return jTextFieldNombreLogro;
    }

    public Logro getLogro() {
        return logro;
    }

    public boolean isSeñal() {
        return señal;
    }

    public int getDueño() {
        return dueño;
    }
}
