/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Logro;
import Modelo.Personas.Niño;
import Modelo.Personas.Profesor;
import Modelo.Registro;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanZea
 */
public class GenerarReporte extends javax.swing.JDialog {

    private ArrayList<Niño> niños;
    private ArrayList<Profesor> profesores;
    private ArrayList<Logro> logros;
    private boolean señal = false;
    private Registro registro;

    /**
     * Esta clase representa una ventana para generar un objeto de la clase reporte.
     *
     * @author JuanZea
     * @version 1.0.0
     * @since Jardin 1.0.2
     */
    public GenerarReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setArrays(ArrayList<Niño> niños, ArrayList<Profesor> profesores, ArrayList<Logro> logros) {
        this.profesores = profesores;
        this.niños = niños;
        this.logros = logros;
    }

    public void rellenarBoxes() {
        for (Profesor profe : profesores) {
            jComboBoxProfesor.addItem(profe.getNombre());
        }
        for (Niño niño : niños) {
            jComboEstudiante.addItem(niño.getNombre());
        }
    }

    public void rellenarLogros(int i) {
        DefaultComboBoxModel box = new DefaultComboBoxModel();
        jComboLogro.setModel(box);
        for (int j = 0; j < niños.get(i).getLogros().size(); j++) {
            jComboLogro.addItem(niños.get(i).getLogros().get(j).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jPanelHoja = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProfesor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboEstudiante = new javax.swing.JComboBox<>();
        jComboLogro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboLogroValoracion = new javax.swing.JComboBox<>();
        jComboDia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboAño = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButtonGenerar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        javax.swing.JLabel jLabelFondo6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar Reporte");
        setIconImage(new ImageIcon(getClass().getResource("/Vista/img/Icono4.png")).getImage());

        jPanelBase.setLayout(null);

        jPanelHoja.setOpaque(false);

        jLabel1.setBackground(java.awt.Color.orange);
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Profesor:");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(java.awt.Color.orange);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Estudiante:");
        jLabel2.setOpaque(true);

        jComboEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstudianteActionPerformed(evt);
            }
        });

        jComboLogro.setEnabled(false);

        jLabel3.setBackground(java.awt.Color.orange);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Logro:");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(java.awt.Color.orange);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Valoracion:");
        jLabel4.setOpaque(true);

        jComboLogroValoracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dificultad", "Aceptable", "Capaz", "Muy Capaz" }));

        jComboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "15" }));

        jLabel5.setBackground(java.awt.Color.orange);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Dia:");
        jLabel5.setOpaque(true);

        jComboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel6.setBackground(java.awt.Color.orange);
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Mes:");
        jLabel6.setOpaque(true);

        jComboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        jLabel7.setBackground(java.awt.Color.orange);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Año:");
        jLabel7.setOpaque(true);

        jButtonGenerar.setText("Generar");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHojaLayout = new javax.swing.GroupLayout(jPanelHoja);
        jPanelHoja.setLayout(jPanelHojaLayout);
        jPanelHojaLayout.setHorizontalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboEstudiante, 0, 155, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboMes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboLogro, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboLogroValoracion, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jComboAño, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelHojaLayout.setVerticalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboLogro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboLogroValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHojaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelHojaLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jButtonGenerar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanelBase.add(jPanelHoja);
        jPanelHoja.setBounds(0, 0, 700, 400);

        jLabelFondo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Fondo6.png"))); // NOI18N
        jPanelBase.add(jLabelFondo6);
        jLabelFondo6.setBounds(1, -4, 700, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstudianteActionPerformed
        rellenarLogros(jComboEstudiante.getSelectedIndex());
        if (jComboEstudiante.getSelectedIndex() != -1) {
            jComboLogro.setEnabled(true);
        }
    }//GEN-LAST:event_jComboEstudianteActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        señal = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        if (jComboBoxProfesor.getSelectedIndex() == -1 || jComboEstudiante.getSelectedIndex() == -1 || jComboLogro.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Hacen uno o varios datos");
        } else {
            int dia = jComboDia.getSelectedIndex();
            int mes = jComboMes.getSelectedIndex();
            int año = jComboAño.getSelectedIndex();
            Profesor profesor = profesores.get(jComboBoxProfesor.getSelectedIndex());
            Niño niño = niños.get(jComboEstudiante.getSelectedIndex());
            Logro logro = logros.get(jComboLogro.getSelectedIndex());
            int valoracion = jComboLogroValoracion.getSelectedIndex();
            registro = new Registro(dia, mes, año, profesor, niño, logro, valoracion);
            señal = true;
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GenerarReporte dialog = new GenerarReporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JComboBox<String> jComboAño;
    private javax.swing.JComboBox<String> jComboBoxProfesor;
    private javax.swing.JComboBox<String> jComboDia;
    private javax.swing.JComboBox<String> jComboEstudiante;
    private javax.swing.JComboBox<String> jComboLogro;
    private javax.swing.JComboBox<String> jComboLogroValoracion;
    private javax.swing.JComboBox<String> jComboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelHoja;
    // End of variables declaration//GEN-END:variables

    public boolean isSeñal() {
        return señal;
    }

    public Registro getRegistro() {
        return registro;
    }
}
