/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 * Esta clase es la principal representacion del programa de manera visual.
 *
 * @author JuanZea
 * @version 1.0.3
 * @since Jardin 1.0.0
 */
public class Ventana extends javax.swing.JFrame {
    
    private int emblema = 0;
    /**
     * Creates new form MenuPrincipal
     */
    public Ventana() {
        initComponents();
        buttonGroup.add(jRadioButton1);
        buttonGroup.add(jRadioButton2);
        buttonGroup.add(jRadioButton3);
        buttonGroup.add(jRadioButton4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanelMenuPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonGenerarReporte = new javax.swing.JButton();
        jButtonAsignarLogro = new javax.swing.JButton();
        jButtonImprimirReporte = new javax.swing.JButton();
        jLabelFondo3 = new javax.swing.JLabel();
        jPanelProfesores = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelListaProfesores = new javax.swing.JLabel();
        jLabelDescripcionProfesores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProfesores = new javax.swing.JList<>();
        jButtonAñadirProfesor = new javax.swing.JButton();
        jButtonEliminarProfesor = new javax.swing.JButton();
        jButtonEditarProfesor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProfesor = new javax.swing.JTextArea();
        jLabelFondo2 = new javax.swing.JLabel();
        jPanelNiños = new javax.swing.JPanel();
        jPanelNiños1 = new javax.swing.JPanel();
        jButtonAñadirNiño = new javax.swing.JButton();
        jButtonEditarNiño = new javax.swing.JButton();
        jButtonEliminarNiño = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListNiños = new javax.swing.JList<>();
        jLabelListaNiño = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaNiños = new javax.swing.JTextArea();
        jLabelDescripcionNiño = new javax.swing.JLabel();
        jLabelFondo4 = new javax.swing.JLabel();
        jPanelAcudientes = new javax.swing.JPanel();
        jPanelAcudientes1 = new javax.swing.JPanel();
        jLabelListaAcudientes = new javax.swing.JLabel();
        jLabelDescripcionAcudientes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAcudientes = new javax.swing.JList<>();
        jButtonAñadirAcudiente = new javax.swing.JButton();
        jButtonEliminarAcudiente = new javax.swing.JButton();
        jButtonEditarAcudiente = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaAcudientes = new javax.swing.JTextArea();
        jLabelFondo5 = new javax.swing.JLabel();
        jPanelConfiguracionBase = new javax.swing.JPanel();
        jPanelConfiguracion = new javax.swing.JPanel();
        txtFNombre = new javax.swing.JTextField();
        txtFCaracter = new javax.swing.JTextField();
        txtFDireccion = new javax.swing.JTextField();
        txtFAño = new javax.swing.JTextField();
        txtFNit = new javax.swing.JTextField();
        txtFMatriculados = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        lblNombre5 = new javax.swing.JLabel();
        btnLimpiarC = new javax.swing.JButton();
        btnGuardarC = new javax.swing.JButton();
        btnTestearC = new javax.swing.JButton();
        lblNombre6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabelFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JARDIN");
        setIconImage(new ImageIcon(getClass().getResource("/Vista/img/Icono.png")).getImage());
        setName("MenuPrincipal"); // NOI18N
        setResizable(false);

        jTabbedPanePrincipal.setBackground(new java.awt.Color(255, 255, 110));
        jTabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPanePrincipal.setOpaque(true);
        jTabbedPanePrincipal.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanelMenuPrincipal.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanelMenuPrincipal.setLayout(null);

        jPanel1.setOpaque(false);

        jButtonGenerarReporte.setText("Generar Reporte");

        jButtonAsignarLogro.setText("Asignar Logro");

        jButtonImprimirReporte.setText("Imprimir Reporte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonAsignarLogro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButtonGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButtonImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAsignarLogro, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanelMenuPrincipal.add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 390);

        jLabelFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Fondo3.png"))); // NOI18N
        jPanelMenuPrincipal.add(jLabelFondo3);
        jLabelFondo3.setBounds(0, 0, 660, 400);

        jTabbedPanePrincipal.addTab("Menu Principal", new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Icono1.png")), jPanelMenuPrincipal); // NOI18N

        jPanelProfesores.setLayout(null);

        jPanel2.setOpaque(false);

        jLabelListaProfesores.setBackground(java.awt.Color.orange);
        jLabelListaProfesores.setForeground(java.awt.Color.black);
        jLabelListaProfesores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaProfesores.setText("LISTA DE PROFESORES");
        jLabelListaProfesores.setOpaque(true);

        jLabelDescripcionProfesores.setBackground(java.awt.Color.orange);
        jLabelDescripcionProfesores.setForeground(java.awt.Color.black);
        jLabelDescripcionProfesores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescripcionProfesores.setText("DESCRIPCION");
        jLabelDescripcionProfesores.setOpaque(true);

        jScrollPane1.setViewportView(jListProfesores);

        jButtonAñadirProfesor.setText("Añadir");

        jButtonEliminarProfesor.setText("Eliminar");

        jButtonEditarProfesor.setText("Editar");

        jTextAreaProfesor.setColumns(20);
        jTextAreaProfesor.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProfesor);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelListaProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliminarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAñadirProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabelDescripcionProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDescripcionProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelListaProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonAñadirProfesor)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarProfesor)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarProfesor)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelProfesores.add(jPanel2);
        jPanel2.setBounds(0, 0, 660, 390);

        jLabelFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Fondo2.png"))); // NOI18N
        jPanelProfesores.add(jLabelFondo2);
        jLabelFondo2.setBounds(0, 0, 660, 400);

        jTabbedPanePrincipal.addTab("Profesores      ", new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Icono3.png")), jPanelProfesores); // NOI18N

        jPanelNiños.setLayout(null);

        jPanelNiños1.setOpaque(false);

        jButtonAñadirNiño.setText("Añadir");

        jButtonEditarNiño.setText("Editar");

        jButtonEliminarNiño.setText("Eliminar");

        jScrollPane3.setViewportView(jListNiños);

        jLabelListaNiño.setBackground(java.awt.Color.orange);
        jLabelListaNiño.setForeground(java.awt.Color.black);
        jLabelListaNiño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaNiño.setText("LISTA DE NIÑOS");
        jLabelListaNiño.setOpaque(true);

        jTextAreaNiños.setColumns(20);
        jTextAreaNiños.setRows(5);
        jScrollPane4.setViewportView(jTextAreaNiños);

        jLabelDescripcionNiño.setBackground(java.awt.Color.orange);
        jLabelDescripcionNiño.setForeground(java.awt.Color.black);
        jLabelDescripcionNiño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescripcionNiño.setText("DESCRIPCION");
        jLabelDescripcionNiño.setOpaque(true);

        javax.swing.GroupLayout jPanelNiños1Layout = new javax.swing.GroupLayout(jPanelNiños1);
        jPanelNiños1.setLayout(jPanelNiños1Layout);
        jPanelNiños1Layout.setHorizontalGroup(
            jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNiños1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelListaNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNiños1Layout.createSequentialGroup()
                        .addGroup(jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliminarNiño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarNiño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAñadirNiño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabelDescripcionNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanelNiños1Layout.setVerticalGroup(
            jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNiños1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelNiños1Layout.createSequentialGroup()
                        .addComponent(jLabelDescripcionNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNiños1Layout.createSequentialGroup()
                        .addComponent(jLabelListaNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelNiños1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelNiños1Layout.createSequentialGroup()
                                .addComponent(jButtonAñadirNiño)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarNiño)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarNiño)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelNiños.add(jPanelNiños1);
        jPanelNiños1.setBounds(0, 0, 660, 390);

        jLabelFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Fondo4.png"))); // NOI18N
        jPanelNiños.add(jLabelFondo4);
        jLabelFondo4.setBounds(0, 0, 660, 400);

        jTabbedPanePrincipal.addTab("Niños                ", new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Icono6.png")), jPanelNiños); // NOI18N

        jPanelAcudientes.setLayout(null);

        jPanelAcudientes1.setOpaque(false);

        jLabelListaAcudientes.setBackground(java.awt.Color.orange);
        jLabelListaAcudientes.setForeground(java.awt.Color.black);
        jLabelListaAcudientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaAcudientes.setText("LISTA DE ACUDIENTES");
        jLabelListaAcudientes.setOpaque(true);

        jLabelDescripcionAcudientes.setBackground(java.awt.Color.orange);
        jLabelDescripcionAcudientes.setForeground(java.awt.Color.black);
        jLabelDescripcionAcudientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescripcionAcudientes.setText("DESCRIPCION");
        jLabelDescripcionAcudientes.setOpaque(true);

        jScrollPane5.setViewportView(jListAcudientes);

        jButtonAñadirAcudiente.setText("Añadir");

        jButtonEliminarAcudiente.setText("Eliminar");

        jButtonEditarAcudiente.setText("Editar");

        jTextAreaAcudientes.setColumns(20);
        jTextAreaAcudientes.setRows(5);
        jScrollPane6.setViewportView(jTextAreaAcudientes);

        javax.swing.GroupLayout jPanelAcudientes1Layout = new javax.swing.GroupLayout(jPanelAcudientes1);
        jPanelAcudientes1.setLayout(jPanelAcudientes1Layout);
        jPanelAcudientes1Layout.setHorizontalGroup(
            jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcudientes1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelListaAcudientes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAcudientes1Layout.createSequentialGroup()
                        .addGroup(jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliminarAcudiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarAcudiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAñadirAcudiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabelDescripcionAcudientes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanelAcudientes1Layout.setVerticalGroup(
            jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcudientes1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAcudientes1Layout.createSequentialGroup()
                        .addComponent(jLabelDescripcionAcudientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAcudientes1Layout.createSequentialGroup()
                        .addComponent(jLabelListaAcudientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAcudientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAcudientes1Layout.createSequentialGroup()
                                .addComponent(jButtonAñadirAcudiente)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarAcudiente)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarAcudiente)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelAcudientes.add(jPanelAcudientes1);
        jPanelAcudientes1.setBounds(0, 0, 660, 390);

        jLabelFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Fondo5.png"))); // NOI18N
        jPanelAcudientes.add(jLabelFondo5);
        jLabelFondo5.setBounds(0, 0, 660, 400);

        jTabbedPanePrincipal.addTab("Acudientes     ", new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Icono5.png")), jPanelAcudientes); // NOI18N

        jPanelConfiguracionBase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelConfiguracionBase.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanelConfiguracionBase.setLayout(null);

        jPanelConfiguracion.setOpaque(false);

        txtFMatriculados.setEditable(false);
        txtFMatriculados.setText("0");

        lblNombre.setBackground(java.awt.Color.orange);
        lblNombre.setForeground(java.awt.Color.black);
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("NOMBRE DE LA INSTITUCIÓN:");

        lblNombre1.setBackground(java.awt.Color.orange);
        lblNombre1.setForeground(java.awt.Color.black);
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre1.setText("CARÁCTER:");

        lblNombre2.setBackground(java.awt.Color.orange);
        lblNombre2.setForeground(java.awt.Color.black);
        lblNombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre2.setText("DIRECCIÓN:");

        lblNombre3.setBackground(java.awt.Color.orange);
        lblNombre3.setForeground(java.awt.Color.black);
        lblNombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre3.setText("AÑO DE FUNDACIÓN:");

        lblNombre4.setBackground(java.awt.Color.orange);
        lblNombre4.setForeground(java.awt.Color.black);
        lblNombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre4.setText("NIT:");

        lblNombre5.setBackground(java.awt.Color.orange);
        lblNombre5.setForeground(java.awt.Color.black);
        lblNombre5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre5.setText("MATRICULADOS:");

        btnLimpiarC.setText("Limpiar");

        btnGuardarC.setText("Guardar");

        btnTestearC.setBackground(java.awt.Color.orange);
        btnTestearC.setText("Testear");

        lblNombre6.setBackground(java.awt.Color.orange);
        lblNombre6.setForeground(java.awt.Color.black);
        lblNombre6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre6.setText("EMBLEMA DE LA INSTITUCIÓN:");

        jRadioButton1.setForeground(java.awt.Color.black);
        jRadioButton1.setText("Emblema 1");
        jRadioButton1.setOpaque(false);

        jRadioButton2.setForeground(java.awt.Color.black);
        jRadioButton2.setText("Emblema 2");
        jRadioButton2.setOpaque(false);

        jRadioButton3.setForeground(java.awt.Color.black);
        jRadioButton3.setText("Emblema 3");
        jRadioButton3.setOpaque(false);

        jRadioButton4.setForeground(java.awt.Color.black);
        jRadioButton4.setText("Emblema default");
        jRadioButton4.setOpaque(false);

        javax.swing.GroupLayout jPanelConfiguracionLayout = new javax.swing.GroupLayout(jPanelConfiguracion);
        jPanelConfiguracion.setLayout(jPanelConfiguracionLayout);
        jPanelConfiguracionLayout.setHorizontalGroup(
            jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConfiguracionLayout.createSequentialGroup()
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                        .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                .addContainerGap(298, Short.MAX_VALUE)
                                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblNombre2)
                                    .addComponent(lblNombre3)
                                    .addComponent(lblNombre4)
                                    .addComponent(lblNombre5)))
                            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombre)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFNit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFAño, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConfiguracionLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTestearC))
                            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                .addComponent(lblNombre6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarC)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarC)))))
                .addGap(29, 29, 29))
        );
        jPanelConfiguracionLayout.setVerticalGroup(
            jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarC)
                    .addComponent(btnGuardarC)
                    .addComponent(lblNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestearC)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelConfiguracionBase.add(jPanelConfiguracion);
        jPanelConfiguracion.setBounds(0, 0, 660, 390);

        jLabelFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Fondo1.png"))); // NOI18N
        jPanelConfiguracionBase.add(jLabelFondo1);
        jLabelFondo1.setBounds(0, 0, 660, 400);

        jTabbedPanePrincipal.addTab("Configuración  ", new javax.swing.ImageIcon(getClass().getResource("/Vista/img/Icono2.png")), jPanelConfiguracionBase); // NOI18N

        jTabbedPanePrincipal.setSelectedIndex(4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarC;
    private javax.swing.JButton btnLimpiarC;
    private javax.swing.JButton btnTestearC;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonAsignarLogro;
    private javax.swing.JButton jButtonAñadirAcudiente;
    private javax.swing.JButton jButtonAñadirNiño;
    private javax.swing.JButton jButtonAñadirProfesor;
    private javax.swing.JButton jButtonEditarAcudiente;
    private javax.swing.JButton jButtonEditarNiño;
    private javax.swing.JButton jButtonEditarProfesor;
    private javax.swing.JButton jButtonEliminarAcudiente;
    private javax.swing.JButton jButtonEliminarNiño;
    private javax.swing.JButton jButtonEliminarProfesor;
    private javax.swing.JButton jButtonGenerarReporte;
    private javax.swing.JButton jButtonImprimirReporte;
    private javax.swing.JLabel jLabelDescripcionAcudientes;
    private javax.swing.JLabel jLabelDescripcionNiño;
    private javax.swing.JLabel jLabelDescripcionProfesores;
    private javax.swing.JLabel jLabelFondo1;
    private javax.swing.JLabel jLabelFondo2;
    private javax.swing.JLabel jLabelFondo3;
    private javax.swing.JLabel jLabelFondo4;
    private javax.swing.JLabel jLabelFondo5;
    private javax.swing.JLabel jLabelListaAcudientes;
    private javax.swing.JLabel jLabelListaNiño;
    private javax.swing.JLabel jLabelListaProfesores;
    private javax.swing.JList<String> jListAcudientes;
    private javax.swing.JList<String> jListNiños;
    private javax.swing.JList<String> jListProfesores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAcudientes;
    private javax.swing.JPanel jPanelAcudientes1;
    private javax.swing.JPanel jPanelConfiguracion;
    private javax.swing.JPanel jPanelConfiguracionBase;
    private javax.swing.JPanel jPanelMenuPrincipal;
    private javax.swing.JPanel jPanelNiños;
    private javax.swing.JPanel jPanelNiños1;
    private javax.swing.JPanel jPanelProfesores;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTextArea jTextAreaAcudientes;
    private javax.swing.JTextArea jTextAreaNiños;
    private javax.swing.JTextArea jTextAreaProfesor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JTextField txtFAño;
    private javax.swing.JTextField txtFCaracter;
    private javax.swing.JTextField txtFDireccion;
    private javax.swing.JTextField txtFMatriculados;
    private javax.swing.JTextField txtFNit;
    private javax.swing.JTextField txtFNombre;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjButtonAñadirProfesor() {
        return jButtonAñadirProfesor;
    }

    public javax.swing.JList<String> getjListProfesores() {
        return jListProfesores;
    }

    public javax.swing.JButton getjButtonEditarProfesor() {
        return jButtonEditarProfesor;
    }

    public javax.swing.JButton getjButtonEliminarProfesor() {
        return jButtonEliminarProfesor;
    }

    public javax.swing.JTextArea getjTextAreaProfesor() {
        return jTextAreaProfesor;
    }

    public javax.swing.JButton getjButtonAñadirNiño() {
        return jButtonAñadirNiño;
    }

    public javax.swing.JButton getjButtonEditarNiño() {
        return jButtonEditarNiño;
    }

    public javax.swing.JButton getjButtonEliminarNiño() {
        return jButtonEliminarNiño;
    }

    public javax.swing.JList<String> getjListNiños() {
        return jListNiños;
    }

    public javax.swing.JTextArea getjTextAreaNiños() {
        return jTextAreaNiños;
    }

    public javax.swing.JButton getjButtonAñadirAcudiente() {
        return jButtonAñadirAcudiente;
    }

    public javax.swing.JButton getjButtonEditarAcudiente() {
        return jButtonEditarAcudiente;
    }

    public javax.swing.JButton getjButtonEliminarAcudiente() {
        return jButtonEliminarAcudiente;
    }

    public javax.swing.JList<String> getjListAcudientes() {
        return jListAcudientes;
    }

    public javax.swing.JTextArea getjTextAreaAcudientes() {
        return jTextAreaAcudientes;
    }

    public javax.swing.JButton getjButtonGenerarReporte() {
        return jButtonGenerarReporte;
    }

    public javax.swing.JButton getjButtonAsignarLogro() {
        return jButtonAsignarLogro;
    }

    public javax.swing.JButton getjButtonImprimirReporte() {
        return jButtonImprimirReporte;
    }

    public javax.swing.JTextField getTxtFAño() {
        return txtFAño;
    }

    public javax.swing.JTextField getTxtFCaracter() {
        return txtFCaracter;
    }

    public javax.swing.JTextField getTxtFDireccion() {
        return txtFDireccion;
    }

    public javax.swing.JTextField getTxtFMatriculados() {
        return txtFMatriculados;
    }

    public javax.swing.JTextField getTxtFNit() {
        return txtFNit;
    }

    public javax.swing.JTextField getTxtFNombre() {
        return txtFNombre;
    }

    public javax.swing.JButton getBtnGuardarC() {
        return btnGuardarC;
    }

    public javax.swing.JButton getBtnLimpiarC() {
        return btnLimpiarC;
    }

    public javax.swing.JButton getBtnTestearC() {
        return btnTestearC;
    }

    public javax.swing.ButtonGroup getButtonGroup() {
        return buttonGroup;
    }

    public int getEmblema() {
        return emblema;
    }

    public javax.swing.JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    public javax.swing.JRadioButton getjRadioButton2() {
        return jRadioButton2;
    }

    public javax.swing.JRadioButton getjRadioButton3() {
        return jRadioButton3;
    }

    public javax.swing.JRadioButton getjRadioButton4() {
        return jRadioButton4;
    }

    public void setEmblema(int emblema) {
        this.emblema = emblema;
    }
}
